[tool.poetry]
name = "aoc"
version = "0.1.0"
description = ""
authors = ["JGMEYER <meyer.justian@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.10.8"
pytest = "^7.2.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
